auto: true

markdown: rdiscount
pygments: true
paginate: 10
paginate_path: "page:num"
permalink: pretty

title: Blog
url: http://liangxiaoping.github.io
feed: /atom.xml
author_info: <a href="http://liangxiaoping.github.io/">Xiaoping Liang</a>
